<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUS5wfbv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUS5wfbv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUS5wfbv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUS5wfbv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUS5wfbv\App_KernelDevDebugContainer([
    'container.build_hash' => 'US5wfbv',
    'container.build_id' => '00eaf99f',
    'container.build_time' => 1697475120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUS5wfbv');
