<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOx8qatC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOx8qatC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOx8qatC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOx8qatC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOx8qatC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ox8qatC',
    'container.build_id' => '32ccd7ff',
    'container.build_time' => 1697455085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOx8qatC');
